from typing import Protocol
from uuid import UUID

from comptis.domain.tenancy.entities import Membership, Organization, Tenant, User


class OrganizationRepository(Protocol):
    async def save(self, org: Organization) -> None: ...
    async def get_by_id(self, id: UUID) -> Organization | None: ...


class TenantRepository(Protocol):
    async def save(self, tenant: Tenant) -> None: ...
    async def get_by_id(self, id: UUID) -> Tenant | None: ...
    # Requires app.current_organization_id set in session (org-scoped RLS policy)
    async def list_by_organization(self, org_id: UUID) -> list[Tenant]: ...


class UserRepository(Protocol):
    async def save(self, user: User) -> None: ...
    async def get_by_email(self, email: str) -> User | None: ...


class MembershipRepository(Protocol):
    async def save(self, membership: Membership) -> None: ...
    async def delete(self, user_id: UUID, tenant_id: UUID) -> None: ...
    async def get(self, user_id: UUID, tenant_id: UUID) -> Membership | None: ...
