from typing import Protocol
from uuid import UUID

from comptis.domain.tenancy.entities import User


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, hashed: str) -> bool: ...


class TokenService(Protocol):
    def create_access_token(self, user_id: UUID) -> str: ...
    def create_refresh_token(self, user_id: UUID) -> str: ...
    def decode(self, token: str) -> dict: ...


class AuthUserRepository(Protocol):
    async def get_by_email(self, email: str) -> User | None: ...
    async def save_with_credentials(self, user: User, password_hash: str) -> None: ...
    async def get_password_hash(self, user_id: UUID) -> str | None: ...
